//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO()
        {
            this.DETALLE = new HashSet<DETALLE>();
            this.TRACKING = new HashSet<TRACKING>();
        }
    
        public int IDE_PED { get; set; }
        public System.DateTime FEC_PED { get; set; }
        public Nullable<System.DateTime> FEN_PED { get; set; }
        public string ENV_PED { get; set; }
        public Nullable<int> CAN_PED { get; set; }
        public string DES_PED { get; set; }
        public string REF_PED { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> IDE_DIS { get; set; }
        public Nullable<int> IDE_CLI { get; set; }
        public Nullable<int> IDE_EMP { get; set; }
        public Nullable<int> IDE_SER { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE> DETALLE { get; set; }
        public virtual DISTRITO DISTRITO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRACKING> TRACKING { get; set; }
    }
}
