//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.DETALLE = new HashSet<DETALLE>();
        }
    
        public int IDE_PRO { get; set; }
        public string NOM_PRO { get; set; }
        public decimal PRE_PRO { get; set; }
        public int STOCK_PRO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> IDE_PROV { get; set; }
        public Nullable<int> IDE_CAT { get; set; }
        public Nullable<int> IDE_MAR { get; set; }
        public string IMG_PRO { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE> DETALLE { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
