//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
            this.SERVICIO = new HashSet<SERVICIO>();
        }
    
        public int IDE_EMP { get; set; }
        public string NOM_EMP { get; set; }
        public string APE_EMP { get; set; }
        public System.DateTime FNA_EMP { get; set; }
        public string COR_EMP { get; set; }
        public string DIR_EMP { get; set; }
        public string FON_EMP { get; set; }
        public string FOT_EMP { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> IDE_DIS { get; set; }
        public Nullable<int> IDE_CAR { get; set; }
        public Nullable<int> IDE_USU { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual DISTRITO DISTRITO { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
    }
}
