//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIO()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public int IDE_SER { get; set; }
        public string NOM_SER { get; set; }
        public string DES_SER { get; set; }
        public Nullable<System.DateTime> FEC_SER { get; set; }
        public Nullable<decimal> PRE_SER { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> IDE_CLI { get; set; }
        public Nullable<int> IDE_EMP { get; set; }
        public string IMG_SER { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
