//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACKING
    {
        public int IDE_TRA { get; set; }
        public System.DateTime DES_TRA { get; set; }
        public Nullable<System.DateTime> FEC_TRA { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> IDE_PED { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
